### ISSUE TITLE
Comment system to posts

### ISSUE THREAD

**Issue by rygos** [MarceauKa/shaark#45]
Please make it possible to allow comments (only for Registered Users) to a Link or Image or Story.

**Comment by MarceauKa** [comment]
Yep, it can be a good idea but need a lot a changes to allow users to register. Maybe a public comment system with grey-listing. Example: you post a comment with username + email + comment. The comment is not displayed and need to be moderated. Once you have been moderated once, your comments are now auto-moderated.

**Comment by rygos** [comment]
Good point. I forget about registration. What about Disqus integration? For this, no registration for shaarli is needed.

**Comment by MarceauKa** [comment]
Nope, the philosophy of Laravel Shaarli is to be third-party free. This is why there's no CDN, no tracker, no cool web services (such Google Fonts, etc).

What do you think about my comment integration?

**Comment by rygos** [comment]
I would also prefer to have my own system. I think moderation is a good thing in itself, but it would also require some effort in the long run. Automatic moderation would be cool, but in the variant suggested by you, it might be a security problem. Everyone can enter a mail+username combination that has already been moderated. 

I suppose it would be better to eventually allow a registration where only one moderation is required.
Guests should always. When commenting as a guest, a captcha would also be worth considering.

**Comment by MarceauKa** [comment]
In my suggestion, email address of the user who's commenting is hidden. So nobody can use the username and the email of an already moderated user. I think it can be a good idea to implements comment system like this and in the future, allowing user to register.

**Comment by wyred** [comment]
> Laravel Shaarli is a self-hosted platform to keep and share your content: web links, posts, passwords and pictures.

I disagree with having a comment system. I would use a blog if I wanted comments.

But if the decision is made to implement a comment system, please keep it disabled by default. :)

**Comment by virtadpt** [comment]
Seconded.  I pick stuff that doesn't have comment support deliberately.  I don't like the idea of the new iteration of Shaarli having comment support, but if it happens, please make it possible to disable it.

**Comment by MarceauKa** [comment]
Released in [1.2.33](https://github.com/MarceauKa/shaark/releases/tag/1.2.33)
