### ISSUE TITLE
Docker / Docker Compose build?

### ISSUE THREAD

**Issue by 4n70w4** [MarceauKa/shaark#62]
It would be very useful to get a docker image and docker-compose.yml for a easy and fast launch.

**Comment by MarceauKa** [comment]
Hi! Thank you for the idea! I also thought about it. Feel free to make a PR if you know how to do it :)

**Comment by MarceauKa** [comment]
Released in [1.2.38](https://github.com/MarceauKa/shaark/releases/tag/1.2.38)
