### ISSUE TITLE
Server error when parsing templates.mailchimp.com

### ISSUE THREAD

**Issue by wyred** [MarceauKa/shaark#66]
This is the website I tried to add:  
https://templates.mailchimp.com/

This is the error in laravel's logs:

> Return value of App\Services\WebParser::grepContent() must be of the type string, null returned {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Return value of App\\Services\\WebParser::grepContent() must be of the type string, null returned at /var/www/redacted/app/Services/WebParser.php:114)

**Comment by MarceauKa** [comment]
Released in [1.2.39](https://github.com/MarceauKa/shaark/releases/tag/1.2.39)
