### ISSUE TITLE
Ability to add custom CSS

### ISSUE THREAD

**Issue by schuhumi** [MarceauKa/shaark#67]
Hi,

fist of all, thank you very much for this great project! It's a pleasure to use, and so pretty too! I really like your new feature with custom JS (#64), and would like to kindly ask if you could do the same for custom CSS tweaks? Of course one can style with JS as well, it's not pretty code though.. And the custom JS box in the settings puts its content at the end of body, while CSS should be in the head of course.

**Comment by MarceauKa** [comment]
Released in [1.2.40](https://github.com/MarceauKa/shaark/releases/tag/1.2.40)
