### ISSUE TITLE
Archive to web archive

### ISSUE THREAD

**Issue by immanuelfodor** [MarceauKa/shaark#73]
Feature suggestion: Optionally send links to the web.archive.org 

For example, Archivebox does this here: https://github.com/pirate/ArchiveBox/blob/master/archivebox/archive_methods.py#L554

Note: one might want to exclude certain URL patterns from submission to the archive, e.g., local IP/host links, private domains, etc. so it'd be great to have an option to add multiple exclude patterns as regex strings.

Another note: one might enter other links to description fields attached to an URL shared, like additional resources to an opening topic, etc. It would be great to parse all URLs from the share.

**Comment by MarceauKa** [comment]
Closed due to inactivity

**Comment by immanuelfodor** [comment]
Hmm, can I reopen it? Or what should have happened in the meantime to keep it open? :) I'm more of a user than a developer to start working on it :)
