### ISSUE TITLE
Shaarlier compatibility

### ISSUE THREAD

**Issue by immanuelfodor** [MarceauKa/shaark#74]
Feature suggestion: [Shaarlier](https://github.com/dimtion/Shaarlier) is a nice Android app that uses the Shaarli REST API to add links from share menus, it'd be great to make Shaark compatible with it.

It involves maintaining the same share API and generating an API key to provide the app access.

**Comment by MarceauKa** [comment]
Hi, thank you for your feedback. Yep it's a nice idea. With the PWA we already can do that, look at our [PwaController](https://github.com/MarceauKa/shaark/blob/dev/app/Http/Controllers/PwaController.php). But this feature need more work to be fully functional. Feel free to make a PR :)

**Comment by MarceauKa** [comment]
Closed due to inactivity

**Comment by immanuelfodor** [comment]
Hmm, can I reopen it? Or what should have happened in the meantime to keep it open? :) I'm more of a user than a developer to start working on it :)
