### ISSUE TITLE
Unable to load i18n file

### ISSUE THREAD

**Issue by ScrumpyJack** [MarceauKa/shaark#75]
Any idea what's going on here?

https://flareapp.io/share/B5ZGynmo#F63

**Comment by MarceauKa** [comment]
Hi, what is your locale configuration? Can you share your `.env` file?

**Comment by ScrumpyJack** [comment]
APP_NAME="Shaark"
# "production" or "local"
APP_ENV=local
# generated with: php artisan key:generate
APP_KEY=base64:string=
# set debug to false in production
APP_DEBUG=true
APP_URL=https://***************
APP_TIMEZONE=Europe/London
# "en", "fr", "de" or "ja"
APP_LANG=en

# others drivers such as "sqlite" are not supported
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=shaark
DB_USERNAME=shaark
DB_PASSWORD=**************

# "file" or "redis" (if configured)
CACHE_DRIVER=file
# "sync" (local), "database" or "redis" (if configured)
QUEUE_CONNECTION=sync
# "file" or "redis" (if configured)
SESSION_DRIVER=redis
SESSION_LIFETIME=120
# "gd" or "imagick" (user in albums)
IMAGE_DRIVER=gd

# optional
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

# "sendmail" or "smtp"
MAIL_DRIVER=sendmail
MAIL_HOST=127.0.0.1
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME="Shaark"

# replace 'default-salt' with a random string
HASHIDS_SALT=default-salt
HASHIDS_MIN_LENGTH=10

# "local" or "ftp"
BACKUP_DRIVER=local
# leave BACKUP_* empty if you're using the "local" driver
BACKUP_HOST=ftp.example.com
BACKUP_PORT=21
BACKUP_USERNAME=
BACKUP_PASSWORD=
BACKUP_TIMEOUT=60
BACKUP_SSL=false

**Comment by MarceauKa** [comment]
Try to run `php artisan optimize`

**Comment by ScrumpyJack** [comment]
Thanks for looking into this. It's a first time install and I'd love to use this great looking app.
Unfortunately, clearing the cache didn't help.

**Comment by MarceauKa** [comment]
Fixed in [1.2.42](https://github.com/MarceauKa/shaark/releases/tag/1.2.42)

**Comment by ScrumpyJack** [comment]
That fixed it. Thank you very much. Really appreciate it.
