### ISSUE TITLE
how to configure mail?

### ISSUE THREAD

**Issue by ScrumpyJack** [MarceauKa/shaark#76]
I am using v1.2.42 production and I'm having difficulty configuring mail.

The config file options are

```
MAIL_DRIVER=sendmail
MAIL_HOST=127.0.0.1
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=hello@example.com
MAIL_FROM_NAME="Shaark"
```

I have the correct settings for my environment

The only way I can see to test email, is for an admin to create a new user. Is that correct?

1) It would be great to have a form in the settings menu to send a test email to see if it all works.
2) are the dependancies for sending email installed with shaark or do i need binaries on the host (like /usr/bin/sendmail)
3) what are the options for MAIL_ENCRYPTION? START_TLS ?
4) If I change the mail settings in .env, do i need to run php artisan shaark:update

**Comment by MarceauKa** [comment]
Hi @ScrumpyJack,

First of all, you can test email in the settings section (in 2-FA section)

Concerning email configuration, your `.env` file seems to be correct. The `php artisan shaark:update` command is only needed when updating application version. After `.env` edit just run `php artisan config:cache`. If you need additional informations about email config you can look at the [official laravel documentation](https://laravel.com/docs/7.x/mail#introduction).

**Comment by ScrumpyJack** [comment]
Thanks. I did look at the laravel docs but they weren't helpful.

I found my answers in config/mail.php

'encryption' => env('MAIL_ENCRYPTION', 'tls'),


Might be a good idea to let users choose sendmail path in the .env too

 `   'sendmail' => env('SENDMAIL_PATH', '/usr/sbin/sendmail -bs'),`

**Comment by MarceauKa** [comment]
The `.env` file is just a default one. You can add to your `.env` any of the config env variables you found in it. Just keep in mind to run `php artisan config:cache` after modifying it.

But I agree we can improve our doc.

**Comment by ScrumpyJack** [comment]
Here is a patch to add  SENDMAIL_PATH and a few helpful comments

```
--- ../mail.php.orig    2020-04-23 14:03:25.435631258 +0100
+++ config/mail.php     2020-05-05 12:16:29.681814561 +0100
@@ -13,7 +13,7 @@
     'encryption' => env('MAIL_ENCRYPTION', 'tls'),
     'username' => env('MAIL_USERNAME'),
     'password' => env('MAIL_PASSWORD'),
-    'sendmail' => '/usr/sbin/sendmail -bs',
+    'sendmail' => env('SENDMAIL_PATH', '/usr/sbin/sendmail -bs'),
     'markdown' => [
         'theme' => 'default',
         'paths' => [
```

```
--- ../.env.example.orig        2020-05-05 12:36:26.538865426 +0100
+++ .env.example        2020-05-05 12:35:51.666598516 +0100
@@ -35,10 +35,15 @@
 
 # "sendmail" or "smtp"
 MAIL_DRIVER=sendmail
+# sendmail path defaults to "/usr/sbin/sendmail -bs"
+# change it here if you use another sendmail compatible MTA
+SENDMAIL_PATH=
+# change these settings if you want to talk SMTP directly
 MAIL_HOST=127.0.0.1
 MAIL_PORT=1025
 MAIL_USERNAME=null
 MAIL_PASSWORD=null
+# set to MAIL_ENCRYPTION to "tls" if required
 MAIL_ENCRYPTION=null
 MAIL_FROM_ADDRESS=hello@example.com
 MAIL_FROM_NAME="Shaark"
```

**Comment by MarceauKa** [comment]
Please make a PR
