### ISSUE TITLE
Problem adding users.

### ISSUE THREAD

**Issue by ScrumpyJack** [MarceauKa/shaark#77]
I can't seem to create a new user. I fill in the form, click Save and nothing happens.

Where can I see the logs of what's going on?

**Comment by MarceauKa** [comment]
All logs are stored in `storage/logs`.

**Comment by MarceauKa** [comment]
Closing to inactivity

**Comment by nickbe** [comment]
Same problem here. Fresh install. Everything else seems to work. Nothing in the log.
Cannot create users

**Comment by MarceauKa** [comment]
Ok, I'll fix that

**Comment by nickbe** [comment]
Thanks! I've created a new ticket under #87 with a few more details.

**Comment by MarceauKa** [comment]
Fixed in [1.2.44](https://github.com/MarceauKa/shaark/releases/tag/1.2.44)

**Comment by nickbe** [comment]
Works perfectly fine now. Thanks for the quick fix 😄
