### ISSUE TITLE
Request: Gitter channel

### ISSUE THREAD

**Issue by ScrumpyJack** [MarceauKa/shaark#78]
Can you set up a gitter channel for this project?

https://gitter.im/

**Comment by MarceauKa** [comment]
Can tell explain to me why it's important to setup a gitter channel?

**Comment by ScrumpyJack** [comment]
Sometimes it helps to have a channel to chat about a project. IRC, Slack, discord, etc.
Gitter IM seems to be the favoured chat environment for projects on github.
