### ISSUE TITLE
Remove dependancy on github.com

### ISSUE THREAD

**Issue by ScrumpyJack** [MarceauKa/shaark#82]
Github went down for several hours today, making my shaark installation unusable and all shaark website would have been down with this error.

`Undefined variable: feed (View: /var/www/shaark/resources/views/layouts/app.blade.php) (View: /var/www/shaark/resources/views/layouts/app.blade.php)`

Please remove the dependancy on github, or at least make it non-fatal so that websites built with shaark don't go down when github has problems

**Comment by MarceauKa** [comment]
You are right! I'll fix that soon or feel free to make a PR!

**Comment by MarceauKa** [comment]
Fixed in [1.2.43](https://github.com/MarceauKa/shaark/releases/tag/1.2.43)
