### ISSUE TITLE
Image handling

### ISSUE THREAD

**Issue by nickbe** [MarceauKa/shaark#86]
The current image handling would probably be better with a different editor and/or a proper image paste/upload mechanism.

Also when Inserting Links it would be much easier with an image/paste mechanism. That way we could just grab a site screenshot and add it to the link or any other post.

**Comment by nickbe** [comment]
I just found the image handling in the album type. I think it would be great to be able to have this kind of image upload/paste mechanic in all types: Story, Link, Chest. That way our walls would look much more interesting AND visually more searchable.

**Comment by MarceauKa** [comment]
It'll be revamped in a new version (see projects)

**Comment by nickbe** [comment]
Great. Thanks!
