### ISSUE TITLE
Creating users currently not working

### ISSUE THREAD

**Issue by nickbe** [MarceauKa/shaark#87]
Nothing's happening - and no log entry.
Workaround: I copied the user directly in the database.

Note: If I want to edit a user then I have to switch between the edit buttons multiple times until it works.

This has been confirmed on a second installation too. Slightly different PHP version and different environment, but still the same problem. Also tested on: https://shaark.mka.ovh - same here.

These are the last messages from the server:
![image](https://user-images.githubusercontent.com/10890765/98451439-c36b9600-2145-11eb-8b25-04efebbae58d.png)

**Comment by MarceauKa** [comment]
Fixed in [1.2.44](https://github.com/MarceauKa/shaark/releases/tag/1.2.44)
