### ISSUE TITLE
Error when trying to play a youtube video

### ISSUE THREAD

**Issue by nickbe** [MarceauKa/shaark#90]
An error occured. Please try again later. (Wiedergabe-ID: 191OeyUpGgdtbB7z)

**Comment by MarceauKa** [comment]
It's related to Youtube (or your link), not Shaark

**Comment by nickbe** [comment]
you're right. Some Youtube links don't seem to work well when included.

**Comment by MarceauKa** [comment]
@nickbe Go to your Youtube link and check if the embed mode is available.

**Comment by nickbe** [comment]
Yep. It wasn't and I wasn't aware of this at all. Thanks for pointing me to that.
Maybe this hint might be something worth writing into the shaark documentation/help section.
