### ISSUE TITLE
Small Improvement - start with empty screen except pinned

### ISSUE THREAD

**Issue by nickbe** [MarceauKa/shaark#94]
I think it would be helpful to be able to start without any posts except the pinned ones. This could be a switch in the settings, allowing us to see only pinned posts and tags.

**Comment by MarceauKa** [comment]
I don't expect to add this. You should add your own tag such as "Read later" or "Important" for example and create a default wall displaying this tag.

**Comment by nickbe** [comment]
...showing an empty wall in return. Well that's good enough I suppose.
