### ISSUE TITLE
Settings unavailable on fresh install.

### ISSUE THREAD

**Issue by ScrumpyJack** [MarceauKa/shaark#97]
Fresh install of  v1.2.44, first time login and I get the following error when going to the settings.

Can see anything in the logs.

![settings](https://user-images.githubusercontent.com/3187469/107122172-f715a380-688d-11eb-8a44-ff65ab2af632.png)

Any ideas?

**Comment by MarceauKa** [comment]
Hi! Did you disabled demo mode?

**Comment by ScrumpyJack** [comment]
i'm not sure what you mean. it's running in production mode if that helps

**Comment by MarceauKa** [comment]
Here's solutions:

1. Check if you have `APP_DEMO=true` in your `.env` file. Then run `php artisan config:cache`
2. Check if your user is admin. In the `users` table, set the column `is_admin` to 1

**Comment by ScrumpyJack** [comment]
thanks, is_admin was 0
